import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

class PortfolioTracker:
    """
    A tool to track the performance of a portfolio generated by the VarianceSelector.
    It takes the allocation DataFrame, queries yfinance for prices on a target date,
    and calculates unrealized Profit & Loss (P&L).
    """

    def __init__(self):
        pass

    def get_performance(self, portfolio_df, target_date=None):
        """
        Calculates portfolio profit on a specific date.

        :param portfolio_df: DataFrame containing columns ['Ticker', 'Shares', 'Actual Cost'].
        :param target_date: String 'YYYY-MM-DD'. If None, uses the most recent market data.
        :return: Tuple (Detailed DataFrame, Dictionary of Summary Metrics)
        """
        if portfolio_df.empty:
            print("Portfolio is empty. No performance to track.")
            return portfolio_df, {}

        # 1. Prepare Tickers and Data
        tickers = portfolio_df['Ticker'].tolist()
        df_track = portfolio_df.copy()
        
        # Ensure Ticker is not the index, so we can merge easily
        if 'Ticker' not in df_track.columns and df_track.index.name == 'Ticker':
            df_track.reset_index(inplace=True)

        print(f"Fetching market data for {len(tickers)} assets...")

        # 2. Fetch Prices from YFinance
        current_prices = {}
        
        # If target_date is today or None, get the latest available price
        if target_date is None or target_date >= datetime.today().strftime('%Y-%m-%d'):
            print("Target date is current/future. Fetching latest real-time/closing prices...")
            try:
                # download(period="1d") is generally faster for bulk than Ticker.info loop
                data = yf.download(tickers, period="1d", progress=False, auto_adjust=True)['Close']
                
                # Handle single ticker vs multiple ticker return structure
                if len(tickers) == 1:
                    current_prices[tickers[0]] = float(data.iloc[-1])
                else:
                    # data.iloc[-1] gives the last row (latest prices)
                    latest_row = data.iloc[-1]
                    for ticker in tickers:
                        # Check if ticker is in columns (handling potential yfinance download failures)
                        if ticker in latest_row.index:
                            current_prices[ticker] = float(latest_row[ticker])
                        else:
                            print(f"Warning: Could not find price for {ticker}")
                            current_prices[ticker] = None
                            
            except Exception as e:
                print(f"Error fetching latest prices: {e}")

        # If target_date is in the past (Backtesting)
        else:
            print(f"Target date set to {target_date}. Fetching historical close...")
            # We fetch a small window to ensure we catch a trading day if the specific date was a weekend
            start_dt = datetime.strptime(target_date, '%Y-%m-%d')
            end_dt = start_dt + timedelta(days=3) # buffer for weekends
            
            try:
                # --- FIX APPLIED HERE ---
                # Explicitly pass start and end dates to capture the specific historical window
                data = yf.download(tickers, start=start_dt, end=end_dt, progress=False, auto_adjust=True)['Close']
                
                if data.empty:
                    print(f"No data found near {target_date}.")
                else:
                    # Take the first available price in our window (closest to target date)
                    target_row = data.iloc[0]
                    for ticker in tickers:
                        if len(tickers) == 1:
                             # Handle single ticker series
                             current_prices[tickers[0]] = float(target_row)
                        elif ticker in target_row.index:
                            current_prices[ticker] = float(target_row[ticker])
                        else:
                            current_prices[ticker] = None
            except Exception as e:
                print(f"Error fetching historical prices: {e}")

        # 3. Calculate P&L
        # Map prices to the dataframe
        df_track['Comparison Price'] = df_track['Ticker'].map(current_prices)
        
        # Handle missing prices (drop or fill) - here we fill with NaN
        missing_data = df_track[df_track['Comparison Price'].isna()]
        if not missing_data.empty:
            print(f"Warning: Missing price data for: {missing_data['Ticker'].tolist()}")

        # Metric Calculations
        df_track['Current Value'] = df_track['Shares'] * df_track['Comparison Price']
        df_track['Profit ($)'] = df_track['Current Value'] - df_track['Actual Cost']
        df_track['Return (%)'] = (df_track['Profit ($)'] / df_track['Actual Cost']) * 100

        # 4. Generate Summary
        total_invested = df_track['Actual Cost'].sum()
        total_value = df_track['Current Value'].sum()
        total_profit = total_value - total_invested
        total_return_pct = (total_profit / total_invested * 100) if total_invested > 0 else 0

        summary = {
            "Target Date": target_date if target_date else datetime.today().strftime('%Y-%m-%d'),
            "Total Invested": round(total_invested, 2),
            "Current Value": round(total_value, 2),
            "Total Profit ($)": round(total_profit, 2),
            "Total Return (%)": round(total_return_pct, 2)
        }

        return df_track, summary